version: '3.9'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis/redis-stack:latest
    environment:
      - REDIS_ARGS=--appendonly yes
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
      - "8001:8001"

  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:8081"

  ifmo-basic-counter:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    image: ifmo-basic-counter:latest
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_DATA_MONGODB_HOST=mongodb
    volumes:
      - ./data:/data
    depends_on:
      - redis
      - mongodb
      - reverse-proxy