server:
  port: 8081
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 60000
  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: admin
      password: admin
      authentication-database: admin
